#!/bin/bash

usage() {
	echo "$0: [-h] [-K] [-k keyfile] [-u user-data] [-V vol_gr]"
}

_abspath() {
	base=$(basename "$1")
	root="$(cd "$(dirname "$1")" && pwd)"
	echo "$root/$base"
}

SSH_KEYS=""
USER_DATA=""
echo "$@"
while :
do
    case "$1" in
	-k)
		SSH_KEYS+="$(_abspath "$2")"
		shift 2
		;;
	-K)
		KEEP_AFTER_STOP="y"
		shift
		;;
	-u)
		USER_DATA+="$(_abspath "$2")"
		shift 2
		;;
	-V)
		vg="$2"
		shift 2
		;;
	-h)
		usage
		exit 0
		;;
	*)
		shift
		break
		;;
    esac
done

echo "ssh keyfile: $SSH_KEYS"
echo "user-data: $USER_DATA"
############################
# Create the container
############################

LXC_ROOT=/etc/lxc
echo "LXC_ROOT is $LXC_ROOT"

uts="$(uuidgen|cut -d- -f1)"
echo "Creating container: $uts"

MAC=$(openssl rand -hex 6|sed 's/\(xx\)/\1:/g; s/.$//')
cd "$LXC_ROOT"
mkdir -p "${LXC_ROOT}/${uts}/rootfs"
sed "s/++NAME++/${uts}/; s/++MAC++/${MAC}/; s/++VG++/${vg:=vg}/;" \
    "${LXC_ROOT}/.lxc-template/config" > "${LXC_ROOT}/${uts}/config"

lvcreate -s ${vg}/lxc-clean -n "${uts}" -L 10G

############################
# Modify the container
############################
mountdir=$(mktemp -d)
mount "/dev/${vg}/${uts}" $mountdir
test x"$SSH_KEYS" = "x" || \
	cp "$SSH_KEYS"  $mountdir/etc/local.d/openssh-key
test x"$USER_DATA" = "x" || \
	cp "$USER_DATA" $mountdir/etc/local.d/user-data
umount $mountdir

############################
# Spawn the container
############################

lxc-start -n "${uts}"

############################
# Destroy the container
############################

test _"$KEEP_AFTER_STOP" = _y && {
    echo "Not destroying container: ${uts}"
} || {
    lvremove -f "${vg}/${uts}"
    rm -rvf "${LXC_ROOT}/${uts}"
}
